name: telegram_docx_to_pdf_bot
on:
  push:
    branches: [ main ]
  pull requests:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install uv
      run: curl - LsSf https://astral.sh/uv/install.sh | sh
    
    - name: Setup Python:
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies with uv
      run: |
        cd telegram_docx_to_pdf_bot
        uv sync

    - name: Build Docker image
      run: |
        cd telegram_docx_to_pdf_bot
        docker build -t telegram-bot .